name: 📖 Documentation Request
description: File a request to improve Secret Network documentation
title: "[DOCS] <title>"
labels: [Documentation]
body:
- type: markdown
  attributes:
    value: |
      Thank you for helping to improve the Secret Network Docs! 🥳
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: email@example.com OR discord#0000
  validations: 
    required: false
- type: dropdown
  id: request_type
  attributes:
    label: What type of request are you making?  
    options:
    - New Content
    - Update Content
    - Broken Link
    - Other
  validations:
    required: true
- type: textarea
  id: request_description
  attributes:
    label: Please describe how you would like to improve our documentation
    description: "What needs to happen for your request to be complete"
    placeholder: |
      The documentation is missing ...
      The following content needs to be updated ...
      There are broken links to ...
  validations:
    required: true
  
