name: 📖 Documentation Request
description: File a request to improve Secret Network documentation
title: "[DOCS] <title>"
labels: [Documentation]
body:
- type: dropdown
  id: request_type
  attributes:
    label: What type of request are you making?  
    options:
    - New Content
    - Update Content
    - Broken Link
  validations:
    required: true
