name: 📖 Documentation Request
description: File a request to improve Secret Network documentation
title: "[DOCS] <title>"
labels: [Documentation]
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to help us create better documentation!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: email@example.com OR discord#0000
  validations: 
    required: false
- type: dropdown
  id: request_type
  attributes:
    label: What type of request are you making?  
    options:
    - New Content
    - Update Content
    - Broken Link
  validations:
    required: true
