name: 📖 Documentation Request
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: dropdown
  id: request_type
  attributes:
    label: What type of documentation request are you making?  
    options:
    - New Content
    - Update Content
    - Broken Link
  validations:
    required: true
