name: 📖 Documentation Request
description: File a request to improve Secret Network documentation
title: "[DOCS] <title>"
labels: [Documentation]
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to raise an issue with our documentation 🤓
      
      You are helping build a new standard of digital privacy 🤫
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more information about your request?
    placeholder: email@example.com OR discord#0000
  validations: 
    required: false
- type: dropdown
  id: request_type
  attributes:
    label: What type of request are you making?  
    options:
    - New Content
    - Update Content
    - Broken Link
    - Other
  validations:
    required: true
- type: textarea
  id: request_description
  attributes:
    label: Please describe your documentation request
    description: "What needs to happen for your request to be complete"
    placeholder: |
      The documentation is missing ...
      The following content needs to be updated ...
      There are broken links to ...
  validations:
    required: true
- type: textarea
  id: examples
  attributes:
    label: Please share anything you believe may help us create better documentation that is separate from your documentation request. 
    description: |
      Links? References?
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to help improve the documentation of Secret Network! 🥳🚀🤫
  
