name: 📖 Documentation Request
description: File a request to improve Secret Network documentation
title: "[Documentation]: "
labels: ["Documentation"]
assignees:
  - stoicnorth
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our documentation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
 - type: checkboxes
  attributes:
    label: What type of documentation request are you making?
    description: You may select more than one
    options:
    - label: Missing Content
    - label: New Content
    - label: Broken Link
